name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  backend-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          cd backend
          make build
      
      - name: Docker Login
        run: |
          cd backend
          make docker-login  

      - name: Docker Push
        run: |
          cd backend
          make docker-push 

  frontend-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          cd frontend
          make build
      
      - name: Docker Login
        run: |
          cd frontend
          make docker-login 

      - name: Docker Push
        run: |
          cd frontend
          make docker-push

